from scripts.charts import most_expensive_models, pie_type, cambios_year, box_plot_prices, top_electric, average_city, most_city, chart_most_brands, chart_most_models

chart_most_brands()
chart_most_models()
most_city()
average_city(1)
average_city(10)
average_city(50)
box_plot_prices()
cambios_year()
top_electric(False)
top_electric(True)
pie_type()
box_plot_prices()
most_expensive_models()
